"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

const translations = {
  en: { dir: "ltr", badge: "Headless. Multi-tenant. Production ready.", title: "One content engine. Every digital experience.", lead: "Create, govern and deliver multilingual stories, media and curated experiences from one secure platform.", explore: "Explore live content", docs: "Read documentation", capabilities: "Everything your content operation needs", capLead: "A complete control plane for structured content, media and delivery—without locking your frontend to a template.", workflow: "From idea to every screen", platform: "See the platform in action", platformLead: "Browse the consumer experience or connect this demo to your own Content Platform application.", links: ["Browse posts", "Open gallery", "Connect an application"], stats: ["Content types", "Languages ready", "Tenant isolation"], footer: "Open-source content infrastructure for modern teams.", features: [["Content studio", "Draft, review, schedule and publish posts, articles, pages, galleries and video."], ["Media intelligence", "Store once, generate responsive variants and safely track every usage and reference."], ["Visual collections", "Build heroes, sliders, banners and grids as ordered, reusable editorial collections."], ["True multi-tenancy", "Isolate applications, teams, tokens, domains and content with tenant-aware access control."], ["Global by default", "Model localized content in English, Persian and Arabic with locale-aware fallback."], ["SEO & analytics", "Manage sitemaps and metadata, record views and understand content performance."], ["Secure delivery", "Use server-side application tokens, signed media access, rate limits and audit trails."], ["API first", "Deliver to web, mobile, kiosks or any client through a clean REST API."]], steps: [["01", "Compose", "Create structured, localized content."], ["02", "Curate", "Arrange campaigns and collections."], ["03", "Govern", "Control roles, schedules and audits."], ["04", "Deliver", "Power every experience with fast APIs."]]},
  fa: { dir: "rtl", badge: "هدلس، چندمستاجری و آماده‌ی تولید", title: "یک موتور محتوا؛ برای تمام تجربه‌های دیجیتال.", lead: "محتوای چندزبانه، رسانه و مجموعه‌های منتخب را در یک پلتفرم امن بسازید، مدیریت کنید و تحویل دهید.", explore: "مشاهده محتوای زنده", docs: "مطالعه مستندات", capabilities: "تمام ابزارهای لازم برای عملیات محتوا", capLead: "یک مرکز کنترل کامل برای محتوای ساختاریافته، رسانه و تحویل؛ بدون وابستگی فرانت‌اند به قالب خاص.", workflow: "از ایده تا همه‌ی نمایشگرها", platform: "پلتفرم را در عمل ببینید", platformLead: "تجربه‌ی عمومی را مرور کنید یا این دمو را به اپلیکیشن خودتان متصل کنید.", links: ["مشاهده پست‌ها", "باز کردن گالری", "اتصال اپلیکیشن"], stats: ["نوع محتوا", "زبان آماده", "جداسازی مستاجر"], footer: "زیرساخت متن‌باز محتوا برای تیم‌های مدرن.", features: [["استودیوی محتوا", "پیش‌نویس، بازبینی، زمان‌بندی و انتشار پست، مقاله، صفحه، گالری و ویدئو."], ["مدیریت هوشمند رسانه", "ذخیره‌ی یک‌باره، ساخت نسخه‌های واکنش‌گرا و ردیابی امن همه‌ی استفاده‌ها."], ["مجموعه‌های بصری", "هیرو، اسلایدر، بنر و گرید را به‌شکل مجموعه‌های مرتب و قابل‌استفاده‌ی مجدد بسازید."], ["چندمستاجری واقعی", "اپلیکیشن‌ها، تیم‌ها، توکن‌ها، دامنه‌ها و محتوا را با کنترل دسترسی دقیق جدا کنید."], ["چندزبانه از ابتدا", "محتوای فارسی، انگلیسی و عربی را با fallback هوشمند زبان مدل‌سازی کنید."], ["سئو و تحلیل", "نقشه سایت و متادیتا را مدیریت و عملکرد محتوا را تحلیل کنید."], ["تحویل امن", "از توکن سمت سرور، دسترسی امضاشده رسانه، محدودیت نرخ و گزارش ممیزی استفاده کنید."], ["API محور", "محتوا را به وب، موبایل یا هر کلاینتی با REST API تحویل دهید."]], steps: [["۰۱", "تولید", "تولید محتوای ساختاریافته و بومی."], ["۰۲", "چینش", "ساخت کمپین‌ها و مجموعه‌ها."], ["۰۳", "نظارت", "کنترل نقش، زمان‌بندی و ممیزی."], ["۰۴", "تحویل", "تغذیه‌ی محصولات با API سریع."]]},
  ar: { dir: "rtl", badge: "بلا واجهة، متعدد المستأجرين، وجاهز للإنتاج", title: "محرك محتوى واحد، لكل تجربة رقمية.", lead: "أنشئ المحتوى متعدد اللغات والوسائط والتجارب المنسقة وأدرها ووزعها من منصة آمنة واحدة.", explore: "استكشف المحتوى", docs: "اقرأ التوثيق", capabilities: "كل ما تحتاجه عمليات المحتوى", capLead: "لوحة تحكم متكاملة للمحتوى المنظم والوسائط والتوزيع، من دون تقييد الواجهة بقالب.", workflow: "من الفكرة إلى كل شاشة", platform: "شاهد المنصة قيد العمل", platformLead: "تصفح تجربة المستهلك أو صِل هذا العرض بتطبيقك الخاص.", links: ["تصفح المنشورات", "افتح المعرض", "ربط تطبيق"], stats: ["أنواع محتوى", "لغات جاهزة", "عزل المستأجر"], footer: "بنية محتوى مفتوحة المصدر للفرق الحديثة.", features: [["استوديو المحتوى", "أنشئ وراجع وجدول وانشر المقالات والصفحات والمعارض والفيديو."], ["إدارة الوسائط", "خزّن مرة واحدة وأنشئ نسخاً متجاوبة وتتبع كل استخدام بأمان."], ["مجموعات مرئية", "أنشئ الأبطال والمنزلقات واللافتات كمجموعات مرتبة قابلة لإعادة الاستخدام."], ["تعدد مستأجرين حقيقي", "اعزل التطبيقات والفرق والرموز والنطاقات والمحتوى بصلاحيات دقيقة."], ["عالمي من البداية", "نمذج المحتوى بالعربية والفارسية والإنجليزية مع بدائل ذكية."], ["SEO وتحليلات", "أدر خرائط الموقع والبيانات الوصفية وافهم أداء المحتوى."], ["توزيع آمن", "استخدم رموز الخادم والوسائط الموقعة وتحديد المعدل وسجلات التدقيق."], ["API أولاً", "وزع المحتوى إلى الويب والهاتف وأي عميل عبر REST API واضحة."]], steps: [["٠١", "أنشئ", "أنشئ محتوى منظماً ومترجماً."], ["٠٢", "نسّق", "رتب الحملات والمجموعات."], ["٠٣", "احكم", "تحكم بالأدوار والجدولة والتدقيق."], ["٠٤", "وزّع", "غذّ كل تجربة بواجهات سريعة."]]},
} as const;

type Locale = keyof typeof translations;

export default function HomePage() {
  const [locale, setLocale] = useState<Locale>("en");
  const t = translations[locale];
  const [adminUrl, setAdminUrl] = useState("http://localhost:3002");
  useEffect(() => { fetch("/api/runtime-config").then(r => r.json()).then(data => setAdminUrl(data.adminUrl)).catch(() => undefined); }, []);
  return <div className="landing" dir={t.dir} lang={locale}>
    <div className="language-switch">{(["en", "fa", "ar"] as Locale[]).map(x => <button key={x} className={locale === x ? "active" : ""} onClick={() => setLocale(x)}>{x.toUpperCase()}</button>)}</div>
    <section className="hero"><div className="hero-copy"><span className="hero-badge"><i />{t.badge}</span><h1>{t.title}</h1><p>{t.lead}</p><div className="hero-actions"><Link className="cta primary" href="/posts">{t.explore} ↗</Link><a className="cta ghost" href={`https://github.com/mahdiporkar/content-platform/blob/main/docs/${locale}/README.md`}>{t.docs}</a></div><div className="mini-stats">{["6+", "3", "100%"].map((n,i)=><div key={n}><strong>{n}</strong><span>{t.stats[i]}</span></div>)}</div></div>
      <div className="product-window"><div className="window-bar"><span/><span/><span/><b>Content Platform / Overview</b></div><div className="window-body"><aside><div className="logo-mark">C</div>{["Overview", "Content", "Media", "Collections", "Analytics"].map((x,i)=><div className={i===0?"selected":""} key={x}><i/>{x}</div>)}</aside><div className="dashboard"><div className="dash-head"><div><small>Workspace</small><h3>Editorial overview</h3></div><button>+ New content</button></div><div className="metrics"><div><small>Published</small><strong>1,284</strong><em>+12.4%</em></div><div><small>Scheduled</small><strong>48</strong><em>Next 7 days</em></div><div><small>Views</small><strong>82.6k</strong><em>+18.2%</em></div></div><div className="chart-card"><b>Content performance</b><div className="chart">{[2,5,4,7,6,9,8,11].map((x,i)=><i key={i} style={{height:`${x*7}px`}}/>)}</div></div></div></div></div></section>
    <section className="feature-section"><span className="section-kicker">PLATFORM</span><h2>{t.capabilities}</h2><p className="section-lead">{t.capLead}</p><div className="feature-grid">{t.features.map(([title,body],i)=><article key={title}><span className="feature-icon">{["✦","◫","◇","⌘","◎","↗","⌁","{ }"][i]}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="workflow"><div><span className="section-kicker">WORKFLOW</span><h2>{t.workflow}</h2></div><div className="steps">{t.steps.map(([n,title,body])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="demo-callout"><div><span className="section-kicker">LIVE DEMO</span><h2>{t.platform}</h2><p>{t.platformLead}</p><div className="hero-actions"><a className="cta light" href={`${adminUrl}/login?demo=1`}>Create a demo workspace ↗</a><Link className="cta outline" href="/posts">{t.links[0]}</Link><Link className="cta outline" href="/gallery">{t.links[1]}</Link></div></div><pre><span>GET</span> /api/v1/content{`\n`}<i>X-Application-Id: your-app</i>{`\n\n`}{`{`}{`\n`}  <b>"status"</b>: "published",{`\n`}  <b>"locale"</b>: "{locale}",{`\n`}  <b>"items"</b>: [...] {`\n`}{`}`}</pre></section>
    <footer><b>Content Platform</b><span>{t.footer}</span><a href="https://github.com/mahdiporkar/content-platform">GitHub ↗</a></footer>
  </div>;
}
